### ISSUE TITLE
crash when trying to export logs

### ISSUE THREAD

**Issue by tonyguadagno** [UWPX/UWPX-Client#125]
## Bevor you create a new issue:

```
- [ x] I searched for similar issues and did not find one
- [ ] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

Bug report (I searched for similar issues and did not find one)
 

## Current behavior:

i click on the "export logs" button, a file is created on my desktop called logs.zip but the program exits abnormally and the log.zip file seems corrupt and cannot be opened

## Minimal reproduction of the problem with instructions:

1.  go to setting->misc->logs
2. click export logs

## Environment:

```
App Version(s): 
v.X.Y.Z <!-- Which version of the App are you using (e.g. v.0.2.0) -->
v.0.23.0.0

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
-[x] 1909
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [x ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [x ] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
I will have a look at it.
Thanks for reporting!

**Comment by COM8** [comment]
Related issues:
https://appcenter.ms/orgs/UWPX/apps/UWPX-Client/crashes/errors/3702089037u/overview

**Comment by tonyguadagno** [comment]
i am getting a 404 on that link, is that me or the link?

**Comment by COM8** [comment]
No, it's just for me as a reference. ;)

**Comment by COM8** [comment]
![Annotation 2020-02-27 181055](https://user-images.githubusercontent.com/11741404/75467921-acf12600-598c-11ea-97a7-a8d169355ce6.png)
I added support for automatically reporting this issue when it occurs in the next release.
I think this is cause by missing permissions for the path.
Could you try exporting your logs again, as soon as you updated to the next release?

The next version of UWPX will be released in a couple of days.

**Comment by COM8** [comment]
Version [0.24.0.0](https://github.com/UWPX/UWPX-Client/releases/tag/v.0.24.0.0) has been released.
@tonyguadagno please update your app and try exporting again.

**Comment by COM8** [comment]
I'm closing this for now.
Feel free to reopen, if this is still a problem.
