### ISSUE TITLE
New updated OMEMO spec Version 0.7.0

### ISSUE THREAD

**Issue by COM8** [UWPX/UWPX-Client#126]
[XEP-0384: OMEMO Encryption](https://xmpp.org/extensions/xep-0384.html) got updated to Version 0.7.0.
We should update our implementation related to the updated XEP.

**Related:** #5

**Comment by Neustradamus** [comment]
@COM8: Please note that I do not know if 0.3.0 was complete before.

**Comment by Neustradamus** [comment]
@COM8: There is a 0.5.0 now.
- https://xmpp.org/extensions/xep-0384.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.5.0.html
- http://www.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0384-0.3.0.html&newfile=https://xmpp.org/extensions/attic/xep-0384-0.4.0.html

**Comment by COM8** [comment]
@Neustradamus  Thanks!

**Comment by Neustradamus** [comment]
@COM8: Good to read it.

Attention : At this time, please add a 0.7.0 branch and keep current 0.3.0...

OMEMO >= 0.4.0 breaks all OMEMO = 0.3.0.

**Comment by COM8** [comment]
I already started working on the new OMEMO 0.7 spec in combination with a complete DB overhaul. 😉
https://github.com/UWPX/UWPX-Client/tree/db_rework

https://github.com/UWPX/UWPX-Client/tree/db_rework/Omemo
