### ISSUE TITLE
XEP-0280 Disabled

### ISSUE THREAD

**Issue by o---** [UWPX/UWPX-Client#127]
## Bevor you create a new issue:

```
- [x] I searched for similar issues and did not find one (or I did not recognize its the same problem)
- [x] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

- Bug report (I searched for similar issues and did not find one)

## Current behavior:
During account setup, **Message Carbons** toggle is set to **enabled**. Once account is added, Message Carbons show as Disabled.   

## Expected behavior:
Message Carbons are responding to toggle value. 

## Minimal reproduction of the problem with instructions:
1. Add a new account with default settings except of unchecking Trusted certificate requirement. 
2. Check Message Carbons status (in my case shows disabled)
3. Go to Settings turn Message Carbons Off
4. Go to Settings, turn Message Carbons On
5. Check Message Carbons status (in my case shows still disabled)

## Environment:
```
App Version(s): 
v.0.25.0.0

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [x] 1909
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc: 

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [x] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```
THANKS FOR YOUR HELP AND THIS GREAT APP :heart:

**Comment by COM8** [comment]
Thanks for reporting this!
I will have a look into it.

**Comment by COM8** [comment]
I was never actually enabling carbons.
Looks like I removed the code for it during refactoring sometime in the past 😂.

**Comment by stevenroose** [comment]
Perhaps make a 0.25.1 release then? This is quite a missing feature..

**Comment by COM8** [comment]
I don't think this is too much of a critical bug. So I would like to keep the monthly release schedule for now. :D
