### ISSUE TITLE
XEPs and RFCs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [UWPX/UWPX-Client#128]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?
- https://github.com/UWPX/UWPX-Client/blob/master/README.md

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/gajimxepsupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by COM8** [comment]
Good idea.
Thanks!

**Comment by Neustradamus** [comment]
@COM8: Excellent, thanks a lot :)
It is easy to update now!
