### ISSUE TITLE
XEP-0084: User Avatar support

### ISSUE THREAD

**Issue by Sylvhem** [UWPX/UWPX-Client#130]
## Bevor you create a new issue:

```
- [x] I searched for similar issues and did not find one
- [x] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

Bug report (I searched for similar issues and did not find one)
 

## Current behavior:

I open UWPX and log in into my existing XMPP account. Contacts listed in my roster doesn’t have an avatar. When opening a conversation, the avatar of the person I’m talking with is not displayed. MUC’s avatars are not displayed either.

## Expected behavior:

Avatar should be displayed for each user and each MUC when available.

## Minimal reproduction of the problem with instructions:
1. Log in to an XMPP account.
2. Click on “Add Chat” or “Add Group Chat (MUC)”.
3. If no JID are suggested, enter one and click on “Add”.

## Environment:

```
App Version(s): 
v.0.25.0.0 <!-- Which version of the App are you using (e.g. v.0.2.0) -->

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [x] 1909
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [x] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
Sadly this is expected behaviour since `UWPX` currently does not support user avatars.
**Reference:**
* [XEP-0084: User Avatar](https://xmpp.org/extensions/xep-0084.html)

It's on my TODO list, but I do not know when I have time for it.

**Comment by COM8** [comment]
Implemented it earlier this year.
https://github.com/UWPX/UWPX-Client/releases/tag/v.0.39.0.0
