### ISSUE TITLE
Something unexpected happened (0x800701C5)

### ISSUE THREAD

**Issue by o---** [UWPX/UWPX-Client#131]
## Bevor you create a new issue:

```
- [X] I searched for similar issues and did not find one
- [X] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

Regression (a behavior that used to work and stopped working in a new release)

## Current behavior:
When installing the app from Microsoft Store, 

![image](https://user-images.githubusercontent.com/5457048/81508256-652f3900-9303-11ea-9cbc-03363e805eaf.png)

## Expected behavior:

The app installs and can be used

## Minimal reproduction of the problem with instructions:

1. Install app from App store

## Environment:

```
App Version(s): 
v.0.25.0.0 worked, installing v0.26.1.0 (latest) fails

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [X] 1909
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [X] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
Hmmm...
The only reason for this could be the changed permissions required by the app (https://github.com/UWPX/UWPX-Client/issues/129#issuecomment-623936651).
I will have to investigate this.

Are you able to update other apps?

**Comment by o---** [comment]
I did not try other apps, but I tried to two different PC.

**Comment by RudeTheJack** [comment]
Me the same!!!!Help!!!!
No problem with other apps!

**Comment by o---** [comment]
Yeah, I tried to install an random app from the App Store. No issue there.

**Comment by o---** [comment]
Regarding the #129 comment, I thought you have made changes because of that. I checked apps permissions but I am not finding anything. And again, I have the same issue again on two different computers.

**Comment by COM8** [comment]
Arg...
This does not sound good.
I'll try to have a look at it later today.

Has anybody tried what happens if you uninstall and then install the app again?

On my side I'm able to install and update the app without any problems.

**Comment by RudeTheJack** [comment]
After the error:0x800701C5 came out, I even couldn't open the old version UWPX (it didn't work after left click). So I tried what you said, but nothing changed!

**Comment by COM8** [comment]
@RudeTheJack thanks for the information.

Since a lot (but not all 🤷🏻‍♂️) people were affected I decided to publish a new version directly without the `broadFileSystemAccess` capability.

It should be available through the store in about one to two hours.
https://github.com/UWPX/UWPX-Client/releases/tag/v.0.26.2.0

**Comment by COM8** [comment]
Please let me know, if this fixes the issue.

**Comment by RudeTheJack** [comment]
OK, I will focus on it by non-stop installing every 5 minutes😂

**Comment by RudeTheJack** [comment]
Done！

**Comment by o---** [comment]
To answer your question above, I tried both methods: 
- updating  -> Error
- uninstalling and reinstalling -> Error

Same on 2 different PC's with what I would call a pretty standard Windows configuration. 

**Now with your latest changes I am up and running again. Thank you!**

**Comment by COM8** [comment]
Never the less, this was/is an interesting bug.
