### ISSUE TITLE
Failed to connect and set push accounts. (while Push notifications are disabled)

### ISSUE THREAD

**Issue by o---** [UWPX/UWPX-Client#132]
## Bevor you create a new issue:

```
- [X] I searched for similar issues and did not find one
- [X] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

Bug report (I searched for similar issues and did not find one)
 

## Current behavior:
UWPX is trying to establish a connection to push.uwpx.org despite of Push notifications being disabled. 

![image](https://user-images.githubusercontent.com/5457048/81668396-eb06cd80-9444-11ea-8b13-a682887be7d2.png)
![image](https://user-images.githubusercontent.com/5457048/81668503-0e317d00-9445-11ea-9a30-d2a189efd0df.png)

## Expected behavior:
UWPX does not connect to push.uwpx.org when push notifications are disabled.  

## Minimal reproduction of the problem with instructions:
1. Enable Push Notifications (despite of not being implemented from server side)
2. Disable Push Notifications
3. Restart application
4. Check logs
5. Check Push Notifications are disabled (in my case Flag says they are)

## Environment:

```
App Version(s): 
v.0.26.2.0

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [X] 1909
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [X] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
This is probably caused by UWPX trying to deactivate all accounts on the push server.
Since you had enabled push once, it thinks it was able to publish accounts successfully.
I will have to fix this.

Btw. thanks for taking the time to report issues!
