### ISSUE TITLE
Minimized but Online possible?

### ISSUE THREAD

**Issue by morbificagent** [UWPX/UWPX-Client#135]
Hi there,

great to see there is a XMPP Client to use with Win10.

Actually i am trying it a little bit and as there are no working Push-Notifications for now i thought i could minimize it and get notified when a message comes in.

But it seams that my account goes offline when i minimize it.

Is this right? Is there any solution to receive messages when the app isnt maximized?

**Comment by COM8** [comment]
Yes, you are right.
When you minimize UWPX, your accounts go offline.
I can not do anything against this, right now.
When you minimize the app, Windows suspends the app to save on battery use.

I'm currently working on push to resolve this issue.

**Comment by morbificagent** [comment]
Ok, then i have to wait and cheer for you ;-)
