### ISSUE TITLE
Thanks for the program!

### ISSUE THREAD

**Issue by mrkaban** [UWPX/UWPX-Client#138]
Thanks for the program under a free open source license! Added a program to a Russian-language site about free open source software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5/uwpx-xmpp-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82.html).

Please do not abandon the project! This is a very interesting program!

Will stable versions be published here?

**Comment by COM8** [comment]
@mrkaban, thanks for your feedback!

I will definitely continue working on UWPX and development will kick back up starting next month.
The last couple of months I was quiet busy preparing, writing and correcting exams.
Now since all of this is over I can focus again on UWPX.
