### ISSUE TITLE
App Crash when deleting account

### ISSUE THREAD

**Issue by o---** [UWPX/UWPX-Client#140]
## Bevor you create a new issue:

```
- [X] I searched for similar issues and did not find one
- [X] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

- Regression (a behavior that used to work and stopped working in a new release)
  
 

## Current behavior:
Application crashes when trying to delete an account. 
There is nothing in the log. 

Following info can be found in the event log:

_Name of the app: UWPX_UI.exe, version: 1.0.0.0, timestamp: 0x5f759893
Name of the missing module: Windows.UI.Xaml.dll, version: 10.0.18362.1139, timestamp: 0x97b8f732
Exception code: 0xc000027b
Error: 0x00000000001a0372
Identification of missing process: 0x3e18
Execution time: 0x01d6a4c69db8625e
Path to application: C:\Program Files\WindowsApps\790FabianSauter.UWPXAlpha_0.28.0.0_x64__s1c5dt7qckd0e\UWPX_UI.exe
Path to missing module: C:\Windows\System32\Windows.UI.Xaml.dll
Full name of missing package: 790FabianSauter.UWPXAlpha_0.28.0.0_x64__s1c5dt7qckd0e
Identification of missing application related to the package: App_

## Expected behavior:
Account can be deleted.

## Minimal reproduction of the problem with instructions:
1. Deactivate account
2. Delete account

## Environment:

```
App Version(s): 
v.0.28.0.0 <!-- Which version of the App are you using (e.g. v.0.2.0) -->

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [X] 1909
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [X] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
Thanks for submitting. I will have a look at it.
Does this happen all the time, or only when the account is trying to connect?

**Comment by o---** [comment]
It is happening every single time. The account only gets deleted when you keep the history. And this also not every single time. So I do not see a pattern there.

**Comment by COM8** [comment]
Ok. Thanks 👍🏻. A fix will be included in next weeks release.
