### ISSUE TITLE
Socket error code: 24 [CertificateUntrustedRoot]

### ISSUE THREAD

**Issue by rvsphinx** [UWPX/UWPX-Client#147]
## Bevor you create a new issue:

```
- [ x] I searched for similar issues and did not find one
- [ x] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

!-- - Bug report (I searched for similar issues and did not find one) -->  
 

## Environment:

```
App Version(s): 
v.X.Y.Z <!-- Which version of the App are you using (e.g. v.0.2.0) -->

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [x ] Insider Build (build number: 20H2 Build 19042.746 )
- [ ] Misc:

Device form factor:
- [ x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [ x] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
Thanks for reporting.
This is usually caused by your PC not trusting the root certificate authority of the servers certificate.
Are you using a private or public server?
In case it's public, which one?

**Comment by rvsphinx** [comment]
I'm using my private xmpp server

**Comment by COM8** [comment]
OK. Then you probably created your own certificate for it. To be able to connect you can disable UWPX certificate checks.
![cert](https://user-images.githubusercontent.com/11741404/107007988-88541f80-6793-11eb-9e0d-2e0dd4801f31.gif)

**Comment by rvsphinx** [comment]
@COM8 Thank you that worked.  Yes I made my own self signed cert.  

Thanks again!
