### ISSUE TITLE
SASL-SCRAM-256 doesn't work.

### ISSUE THREAD

**Issue by maranda** [UWPX/UWPX-Client#153]
## Bevor you create a new issue:

```
- [X] I searched for similar issues and did not find one
- [X] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

Bug report (I searched for similar issues and did not find one)
 

## Current behavior:

it seems like there's a problem with UWPX SASL-SCRAM-256 implementation, I think there's something odd with the calculated proof UWPX provides as XOR fails on it.
This was tested on lightwitch.org

## Expected behavior:

XOR not failing

## Minimal reproduction of the problem with instructions:

Just try to login with an account on lightwitch.org

## Environment:

```
App Version(s): 
v.X.Y.Z <!-- Which version of the App are you using (e.g. v.0.2.0) -->

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [ ] 1809
- [ ] 1803
- [X] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [X] Misc: 20H2

Device form factor:
- [X] Desktop
- [X] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [X] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
Thanks for reporting!
I will have a look at it shortly.
