### ISSUE TITLE
Reminder: Update time stamp at XSF website

### ISSUE THREAD

**Issue by Echolon** [UWPX/UWPX-Client#154]
https://github.com/xsf/xmpp.org/blob/91a55856c01489d6b0e0d77f526aec5eb9b5b1e7/data/clients.json#L647

@COM Kannst du mich mal auf meine JID anschreiben. Ich erreiche dich da garnicht mehr :(

**Comment by COM8** [comment]
https://github.com/xsf/xmpp.org/pull/930
For now I did not include the `doap` entry until we had time to finish it up.
