### ISSUE TITLE
Failed to build OMEMO session for: CONTACT@SERVER with: TARGET_DOES_NOT_SUPPORT_OMEMO

### ISSUE THREAD

**Issue by o---** [UWPX/UWPX-Client#156]
## Bevor you create a new issue:

```
- [x] I searched for similar issues and did not find one
- [x] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

- Bug report (I searched for similar issues and did not find one) 
 

## Current behavior:
I am not able to send nor receive any OMEMO encrypted messages. I am seeing the following errors in the log:

- #134 

- [OmemoSessionBuildHelper] Failed to establish session - CONTACT@SERVER doesn't support OMEMO: type: CANCEL, name: ITEM_NOT_FOUND, message: ""

- Failed to build OMEMO session for: CONTACT@SERVER with: TARGET_DOES_NOT_SUPPORT_OMEMO

The Contact is using Conversations Android client. On server side prosody. 

I tried to uninstall the APP and somehow "reset" it just to make sure nothing keeps hanging from previous versions but I am not sure if I succeeded. 
Perhaps #151? If not can you suggest how to completely remove the APP to start "fresh"? 

Lastly #144 sounded similar at first, but the user there is reporting to be able at least to send OMEMO, since I am not, I think this is might be another issue. 

## Expected behavior:
OMEMO exchanges work between apps supporting OMEMO. (UWPX <--> Conversations)

## Environment:

```
App Version(s): 
v.0.31.0.0

Windows 10 Version Number: 
- [X] 21H1
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [X] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
This might be cause by UWPX only supporting OMEMO [0.7.0 (2020-09-05)](https://xmpp.org/extensions/xep-0384.html).
As far as I'm aware, UWP is the first client that "fully" supports OMEMO [0.7.0 (2020-09-05)](https://xmpp.org/extensions/xep-0384.html). So talking to other clients might be difficult.

But I definitely should give the user a better explanation why OMEMO is failing here.

**Comment by o---** [comment]
In #144 another user is reporting being able to send messages to the same android client. 
Its of course great, that UWPX does support the latest OMEMO version 🥇. 
At the same time, if its the only client out there.... it's kind of sad you can only communicate with other PC users.  So if the other client truly does not support the latest OMEMO (Author of this particular android client is one of the co-authors of the OMEMO XEP) a bit of backward compatibility would not hurt.

**Comment by COM8** [comment]
The problem here is, OMEMO 0.7 changed so much, that I would have to maintain two mostly different encryption standards, which is more or less out of scope for me alone. I would like to focus my work on fixing and enhancing my current OMEMO implementation instead of fixing the old one.

As far as I'm aware Dino already supports it too, but there is no release yet I think.

**Comment by COM8** [comment]
I'm closing this one since UWPX now supports OMEMO 0.8.1 and this issue is about incomatibility between OMEMO versions, which is intended.
