### ISSUE TITLE
Onboarding: Use curated list of XMPP Providers

### ISSUE THREAD

**Issue by Echolon** [UWPX/UWPX-Client#158]
Hello,

Here is my suggestion to make use of the curated server list from the [XMPP Providers project](https://invent.kde.org/melvo/xmpp-providers). Transparency: Yes it is another project where I am involved in.

The advantage is that it can simply ready via JSON and, that's what I highly recommend, can make use of guiding users directly to the right support address if they have one of those domain. It can also offer many other options, as randomized distribution of user but also allocation based on e.g. users choice by country / suggestions based on IP / device language. We can also automatically register the user to the relevant support chat / or admin JID.

If you clone the repository and run the script you get three categories. Category A has the best ranking and also only list servers which support IBR (in-band registration). The output lists only list the servers an no details, but if it is of interest to make use of some details, those need to be exported as well. Bear in mind that the C lists might have servers with bad properties of any kind. So I do not recommend to take the bare list.

Also happy to hear your feedback to the project. Let me know if there are technical questions.

**Comment by COM8** [comment]
I will try to add support for this shortly.
