### ISSUE TITLE
Unable install from Microsoft Store

### ISSUE THREAD

**Issue by tcreek** [UWPX/UWPX-Client#163]
The MS store as well as the UWPX site indicates there is a version for Windows Phone.

However, I am unable to install from the store to due requirements constraint of not having a high enough version of Windows Phone. There is no higher version

![viber_image_2021-09-06_11-28-33-227](https://user-images.githubusercontent.com/4149717/132245001-8b863b66-f592-4db2-9607-572963cab008.jpg)

## Possible Fix

Back down the minimum version to install from the Microsoft Store

**Comment by COM8** [comment]
You are right, there is a version for phones, or better phone sized devices.
Indirectly there is a higher version if you have a look at the [WOA](https://github.com/WOA-Project/WOA-Deployer-Lumia) project.
But this comes with a lot of tradeoffs.

I'm currently unable to decrease the minimum required version since all my dependencies require at least this version.

**Comment by tcreek** [comment]
I don't have a Lumia, thus won't be able to install that from the WOA Project

Gook luck with this project anyway.

**Comment by tcreek** [comment]
With Windows 10 Andromeda , Windows 10X both cancelled, and Windows 11 on the horizon, I wonder about the possibility of asking MS to open source Windows 10 Phone.

**Comment by COM8** [comment]
I would love W10 Mobile being open source and I full-heartedly would love to contribute/maintain it then.
But even if MS decides to open source W10 Mobile, there is much more to it, than just the OS.
You also need other stuff like drivers to be open source so we can update them for running on our OS.
I can ensure you Windows does not only contain code from MS, so they would have to ask each stakeholder if it's ok to open source their code as well.

**Comment by tcreek** [comment]
Drivers do not need to be open source, but it is helpful. There are already a lot of open source drivers in the Linux community. I am sure those could work. Already, UBPorts (Ubuntu Touch) uses the Android drivers so they can support many devices. I think many more drivers could be written up, or ported over from Linux, or Android due to using similar ARM based hardware.
