### ISSUE TITLE
CONNECT_TIMEOUT

### ISSUE THREAD

**Issue by Keller18306** [UWPX/UWPX-Client#167]
## Description
just downloaded the app from winstore and added my accounts

## Expected Behavior
I have not used this application, but accounts should be added

## Actual Behavior
writes an error: CONNECT_TIMEOUT
![image](https://user-images.githubusercontent.com/23178771/142509974-0c8c9864-8b79-4a3e-91e5-d0636efeb707.png)

## Possible Fix
i don't know

## Steps to Reproduce
follow initial screen

## Context
I wanted to communicate with a friend, but apparently not destiny ...

## Your Environment

* App Version(s): v.0.16.0
* Device form factor (Desktop, Mobile, Xbox, Surface Hub, ...): Desktop
* Where did you get it from (e.g. Store, Sideload, git, ...): Store first, and then Manual Installation from releases
* Operating System and version: Win10 21H1 19043.1348

**Comment by COM8** [comment]
Sorry for my delayed response, was gone the last couple of days :)
Thanks for your well written issue!

You noted, you are using version `v.0.16.0` of the app. Are you sure about that? If not what does it say, when you got to `Settings` and have a look at the bottom?

I tried it my self and I can connect to `conversations.im` and `404.city` without any problems. Are you behind some kind of proxy/firewall?
Could you please provide the logs? For this go to `Settings` -> `Misc` and click on `Export logs`.

**Comment by COM8** [comment]
Closing this one for inactivity. Feel free to reopen in case this issue still exists.
