### ISSUE TITLE
Freeze/loop in external code adding conference.trashserver.net MUC

### ISSUE THREAD

**Issue by starfrost013** [UWPX/UWPX-Client#170]
## Description

I `git clone`d UWPX and built it. Once it loaded I signed up an account with https://trashserver.net/ and started communicating with my friend. This went mostly acceptably. After that, my friend added me to a conference.trashserver.net MUC and I attempted to add the chat using UWPX's UI. 

At this point, the program froze and I was never added to the MUC even after restarting. VS showed that the program was running external code. No UI response is possible, all threads seem to be blocked. 

## Expected Behavior
The user account is added to the MUC.

## Actual Behavior

The program freezes, with all threads blocked, and must be terminated via Task Manager or other as it is not responding to window messages or user input.

## Possible Fix

Possibly a deadlock, issue with protocol versions, or await issue?

## Steps to Reproduce

1. Create a MUC on https://conference.trashserver.net
2. Add an account to this MUC (preferably one registered using trashserver.net)
3. Use the UWPX UI to add the MUC to the user account.
4. The program will then freeze.

## Context

See above

## Your Environment

* App Version(s): Latest commit (https://github.com/UWPX/UWPX-Client/commit/2444a75c8336f1d70d6d013fb6b99de7b420267e) 
* Device form factor (Desktop, Mobile, Xbox, Surface Hub, ...): Desktop
* Where did you get it from (e.g. Store, Sideload, git, ...): git clone, then build using VS2022 v17.0.5 with the following extensions installed: [vse.txt](https://github.com/UWPX/UWPX-Client/files/8191642/vse.txt)
* Operating System and version: Windows 11, Insider Dev (10.0.22567.1.ni_release.220225-1325)

**Comment by COM8** [comment]
Thanks for reporting this!
Could you please try pulling the latest changes from master and then retry.
I fixed a couple of related issues and I hope this fixed it as well since updating the DB failed in one task and then we did not unlock the DB again. This should be fixed now.

**Comment by starfrost013** [comment]
Alright!

**Comment by COM8** [comment]
Is this still happening?

**Comment by starfrost013** [comment]
Confirmed working on latest commit a017653bc133d8c1fbedfac84bc3d940b82b2248 on Win11 10.0.22598.200 x64. Compiled from source on VS2022 17.1.1
