### ISSUE TITLE
Reopening issue #174 as I have another question 

### ISSUE THREAD

**Issue by jhubler99** [UWPX/UWPX-Client#175]
Hi @COM8, 

Thank you for your quick response. However, SMS is handled through Cheogram and JMP. As far as XMPP is concerned a "sms group chat" is just a really long single Jabber ID that it is communicating with. It never touches the MUC component of XMPP. For example if I want to send a group text message to three recipients, I would use: `number1,number2,number3@cheogram.com`. If I use this Jabber ID, I can send message through the UWPX client but not receive the messages. However, I can receive the messages on my Movim account. Is it possible that the UWPX client is silencing Jabber ID's that is not in my contact list? 

Thank you

_Originally posted by @jhubler99 in https://github.com/UWPX/UWPX-Client/issues/174#issuecomment-1120285370_

**Comment by COM8** [comment]
Totally overlooked this issue. Again, could you please post some logs here 😁?

But in theory UWPX should display it as soon as the first message arrives.

**Comment by jhubler99** [comment]
I set the `Log-Level` to `Trace`. I texted a group of people so there should be a good log. Here is an overview with the time stamps that I sent/received messages: 

- **10:59** - Sent message to this Jabber ID (`number1,number2@cheogram.com`) via UWPX. 
- **11:03** - Received message in UWPX from one of the recipients.
- **11:05** - Received message in UWPX from the other recipient. 
- **11:08** - Received message in UWPX from one of the recipients.
- **11:14** - Sent message to this Jabber ID above. 
- **11:23** - Received message in UWPX from one of the recipients.
- **11:25** - Sent message to a different Jabber ID with same syntax (`number1,number2@cheogram.com`) except with different numbers via UWPX. 
- **11:28** - Received message in UWPX from one of the recipients from this current Jabber ID. 
- **12:00** - Received message in UWPX from original Jabber ID as per **10:59**
- **12:06** - Did NOT receive message in UWPX from one of the recipients. Received in Movim though. 
- **12:12** - Did NOT receive message in UWPX from a Jabber ID. Received in Movim though. 

Attached is the `Logs` directory. [UWPX Logs.zip](https://github.com/UWPX/UWPX-Client/files/8665392/UWPX.Logs.zip)
Thank you for looking into this!

_Originally replied in issue #174: https://github.com/UWPX/UWPX-Client/issues/174#issuecomment-1122978102_

**Comment by COM8** [comment]
All messages described here that got "lost", have never been received by UWPX. What you could try is: Create the chat for `number1,number2,number3@cheogram.com`. Switch to it and then UWPX should try to fetch your message archive from your server. This should then display any messages cached by the server for UWPX.

**Comment by jhubler99** [comment]
Hi @COM8, 

I am closing this issue as it is a duplicate issue with #174.
