### ISSUE TITLE
Not receiving offline messages

### ISSUE THREAD

**Issue by COM8** [UWPX/UWPX-Client#27]
## Bevor you create a new issue:

```
- [ x ] I searched for similar issues and did not find one
- [ x ] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

- Regression (a behavior that used to work and stopped working in a new release)
  
 

## Current behavior:

The client wont receive any offline messages.

## Expected behavior:

Receive offline messages once connection got established.

## Minimal reproduction of the problem with instructions:
1. Disconnect client
2. Send message to client from an other client
3. Connect client again

## Environment:

```
App Version(s): 
v.4.0.0 <!-- Which version of the App are you using (e.g. v.0.2.0) -->

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [ ] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ x ] 1607
- [ x ] 1511
- [ x ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [ x ] Desktop
- [ x ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [ x ] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
Sometimes it works and sometimes it doesn't. Currently not really sure when and when not...

**Comment by COM8** [comment]
Does not seem to occur anymore.

**Comment by COM8** [comment]
If you lose the connection to the internet, it takes the server a vew seconds to realise it.
So he will continue sending messages that never get received (TCP should prevent this but hey...)
Solution: Stream Management [XEP-0198](https://xmpp.org/extensions/xep-0198.html "XEP-0198")

**Comment by COM8** [comment]
6d2d6b6e7d37db3732724c5027555fddf239b057 adds a workaround for this until I was able to add Stream Management [XEP-0198](https://xmpp.org/extensions/xep-0198.html "XEP-0198") support.

**Comment by Echolon** [comment]
Yes, it seems that you never receive my OMEMO messages. You should definitely check this out.

**Comment by COM8** [comment]
Yeah, this is related to #55.
[sqlite-net-pcl](https://github.com/praeclarum/sqlite-net) doesn't really like it if I do a lot of transactions at once like inserting all OMEMO per keys...
This results in me having a broken SQLite connection where every further interaction with the DB fails.

**Comment by COM8** [comment]
Should be fixed now with push support.
