### ISSUE TITLE
Can't login with DIGEST-MD5 : SASL NOT_AUTHORIZED

### ISSUE THREAD

**Issue by amselem** [UWPX/UWPX-Client#30]
## Bevor you create a new issue:

- [X] I searched for similar issues and did not find one
- [X] I'm using the latest version available in the [Windows Store]

## Current behavior:

I can't login in a XMPP Prosody server. Pidgin does login ok. I analyzed logs and found that pidgin is sending this:
auth mechanism='DIGEST-MD5'

however UWPX is sending:
auth mechanism='SCRAM-SHA-1'

resulting in SASL NOT_AUTHORIZED login error in UWPX

Can you add SASL /  DIGEST-MD5 support  to UWPX?

Thank you

## Expected behavior:

I should Login!

## Minimal reproduction of the problem with instructions:
Configure prosody xmpp server 0.9.7 then try to login with UWPX

## Environment:

```
App Version(s): 
v.X.Y.Z <!-- Which version of the App are you using (e.g. v.0.2.0) -->

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [X] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [X] Desktop
- [X] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [X] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
Thanks for reporting!
Could you please go into "Settings" -> "Misc" and change the "Log-Level" to "DEBUG".
Then try to connect.
Now can you open the loggs and post the ```<stream:features>``` containing the available ```<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>```.
e.g.:
```
<stream:features>
	<mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
		<mechanism>
			PLAIN
		</mechanism>
		<mechanism>
			SCRAM-SHA-1
		</mechanism>
		<mechanism>
			SCRAM-SHA-1-PLUS
		</mechanism>
	</mechanisms>
</stream:features>
```
The reason for this is:
UWPX currently only supports ```PLAIN``` authentification.
I will look into it and add more secure auth. mechanisms.

**Comment by amselem** [comment]
Hello, these are the mechanism announced by my prosody server:
Received from (server):
<?xml version='1.0'?>
  <stream:features>
    <register xmlns='http://jabber.org/features/iq-register'/>
    <mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
      <mechanism>SCRAM-SHA-1</mechanism>
      <mechanism>DIGEST-MD5</mechanism>
    </mechanisms>
  </stream:features>

I realized that PLAIN wasn't in the list so I reconfigured the server to allow PLAIN and UWPX is now connecting!

SCRAM-SHA-1 and/or DIGEST-MD5 support would be nice, indeed

Regards

**Comment by COM8** [comment]
Ok thanks for your reply - will have a look into it

**Comment by COM8** [comment]
So the current state is:
I'm working on it, but I have a problem with the ``PBKDF2_SHA_1` hashing not returning the correct hashes.
It might take some additional time for me to fix this.

**Comment by COM8** [comment]
I decided I won't add DIGIST-MD5 support because it has been decalred as [obsolete](https://tools.ietf.org/html/rfc6331).
Instead I will try to add SCRAM-SHA-1-PLUS support

**Comment by COM8** [comment]
Next months release (v.0.9.0.0) should add SCRAM-SHA-1 support
