### ISSUE TITLE
Website: Direct download + Windows 7

### ISSUE THREAD

**Issue by Echolon** [UWPX/UWPX-Client#43]
Hi,

I've got two questions:

- Would it be possible to offer a direct download of the .exe from the website? I think this would increase Devs and people to test it and may contribute.

- Would a windows 7 client be possible or in scope? Same point here

Cheers

**Comment by COM8** [comment]
Sadly **No**.
* I'm not able to create a Windows 7 package. The min. build of Windows 10 you need is: `10.0.15063.0`
* I don't know any way to package an UWP app as .exe and (correct me if I'm wrong) I don't think there is any
* For every release I also include a "sideloading package" so I don't depend on the MS Store ;-)

**Comment by Echolon** [comment]
Alright, thanks.

I also have no idea about windows anymore - as I use Linux for 3-4 years already.

Still looking forward to this app release!
