### ISSUE TITLE
Xbox support

### ISSUE THREAD

**Issue by COM8** [UWPX/UWPX-Client#48]
Need somebody who can validate/test if UWPX is running on an Xbox (one (x)) so I can make UWPX available in the Xbox Store.
https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/

**Comment by singpolyma** [comment]
Would it help if you had the funds to buy an xbox (probably series x would be best at this point?) for development and testing purposes?  Let's talk: JID is singpolyma@singpolyma.net

**Comment by LAGonauta** [comment]
It works well 😊
But no background messaging support (Xbox kills the app on app switch), push notification should help with that.

**Comment by COM8** [comment]
Closing this, since it is working and push notifications are on their way :)

**Comment by LAGonauta** [comment]
Hello!
Sadly Uwpx does not work in my Xbox anymore :/
It crashes on startup, no idea if you can see it on application insights

**Comment by COM8** [comment]
@LAGonauta thanks for reporting. I'm seeing a bunch of crashes related to avatars in unsupported formats, but none reported from an Xbox. Do you have an avatar set for your account?

**Comment by LAGonauta** [comment]
Just reinstalled to clear any cache.
My account has an avatar, but I do not think this crash is related to them. When I open the app it immediately closes after showing the splash screen for less than a second, maybe .NET is crashing before anything loads? Therefore, no analytics.

Sadly I have no idea how to get some logs on the Xbox :/

**Comment by COM8** [comment]
I released [v.0.40.1.0](https://github.com/UWPX/UWPX-Client/releases/tag/v.0.40.1.0) which has a bunch of bug fixes included. Could you please try with this release again? If it still does not work I will have to ask people at the university again if I can borrow their console again :D

**Comment by LAGonauta** [comment]
The newest version loads, but crashes after login. Hopefully you got some logs to work with now :+1:

**Comment by COM8** [comment]
Sadly no :(
Perhaps it crashes too early. I will have a deeper look at it next week, when my exams are over 😁.
I created a new issue for it #169
