### ISSUE TITLE
Support for gtalk

### ISSUE THREAD

**Issue by seba76** [UWPX/UWPX-Client#54]
## Bevor you create a new issue:

```
- [x ] I searched for similar issues and did not find one
- [x] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:

  
- Feature request (UserVoice request: )

Currently I'm using pidgin to connect to gtalk server. But would like to be able to use UWPX for it if possible. 

## Current behavior:

Connect error

## Expected behavior:

Sucessfull connection and ability to chat.

## Minimal reproduction of the problem with instructions:
1. Create new connection
    Server address: talk.google.com
    Server Port: 5223
    Username: youremail@gmail.com
2. Save

## Environment:

```
App Version(s): 
v.0.12.0 <!-- Which version of the App are you using (e.g. v.0.2.0) -->

Windows 10 Version Number: <!-- https://en.wikipedia.org/wiki/Windows_10_version_history -->
- [x] 1809
- [ ] 1803
- [ ] 1709
- [ ] 1703
- [ ] 1607
- [ ] 1511
- [ ] 1507
- [ ] Insider Build (build number: )
- [ ] Misc:

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [ ] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [x] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] <!-- When did you clone the repo! -->
- [ ] Misc, got it from... <!-- Please tell us your source! -->

```

**Comment by COM8** [comment]
It works for me:
Please make sure you uncheck "Valid name" in "Certificate requirements".
![image](https://user-images.githubusercontent.com/11741404/52402515-c1822800-2ac4-11e9-9927-b3cb13c76a8b.png)

**Comment by seba76** [comment]
Thanks for the tip, that worked. I guess there is a UI bug since port shows 5222 even when I enter 5223 and if I click info 
![image](https://user-images.githubusercontent.com/12673566/52419787-19cf1f00-2af1-11e9-8544-89580aa3e81e.png) apps crashes.
Also do you get roster?
![snip](https://user-images.githubusercontent.com/12673566/52419708-e8eeea00-2af0-11e9-9342-6a0bd2f76920.jpg)

**Comment by COM8** [comment]
Yes looks like a UI related bug.
Could you please upload your logs ("Settings" -> "Misc" -> "Export logs" and upload the zip file).
Please make sure: If you have changed the log level to **debug** and tried to connected the logs will contain your password, so delete it before uploading your logs.

Thanks!

**Comment by seba76** [comment]
Here is a log file, I've obfuscated emails and pass.
[Logs.zip](https://github.com/UWPX/UWPX-Client/files/2844037/Logs.zip)

**Comment by seba76** [comment]
I clicked close by accident so reopening it again.

**Comment by COM8** [comment]
Thanks! Spotted two problems:
#### `Failed to load OMEMO prekeys`
I really have to find an other way to store all the stuff locally [sqlite-net-pcl](https://github.com/praeclarum/sqlite-net) is far not well enough maintained and so far to buggy...

#### Requesting the roster fails with `bad-request` (`If set, the 'from' attribute must be set to the user's full JID.`)
UWPX sends the following valid roster query:
```XML
<iq type="get" id="9f039e98-bacd-4eb3-8c2f-389fe9a23943" to="sxxxxxxxxxx@gmail.com" from="sxxxxxxxxxx@gmail.com/YYYYYYY">
  <query xmlns="jabber:iq:roster" />
</iq> 
```
Looks like it want's `from="sxxxxxxxxxx@gmail.com/YYYYYYY"` to be `from="sxxxxxxxxxx@gmail.com"`.

**Comment by Echolon** [comment]
Is gtalk, really a thing to work on now? I would ask for a PR

**Comment by COM8** [comment]
I'm not working on this right now since gtalk is more or less dead.
