### ISSUE TITLE
Emoji keyboard scrolling

### ISSUE THREAD

**Issue by hooddy** [UWPX/UWPX-Client#68]
## I'm submitting a...:
Emoji keyboard have a bug with scrolling on mobile

  

## Current behavior:
![wp_ss_20190905_0002](https://user-images.githubusercontent.com/6899176/64351940-dd6e8d80-d003-11e9-8fee-922718dd7de0.png)
Mostly emojis layers wonscrolling exepct faces/actions/hands etc layer.

## Environment:

App Version(s): 
- 0.19.0.0

Windows 10 Version Number: 
- 1709

Device form factor:
- Mobile

Where did you got the APP from?
- [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)

**Comment by hooddy** [comment]
Stupid me. Its my mobile issue not UWPX. Sorry.

**Comment by COM8** [comment]
Happy I could help 😉 
Thanks for reporting anyway 😄
