### ISSUE TITLE
"Enter to send" setting doesn't work reliably

### ISSUE THREAD

**Issue by JKingweb** [UWPX/UWPX-Client#70]
## Before you create a new issue:
```
- [x] I searched for similar issues and did not find one
- [x] I'm using the latest version available in the [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
```

## I'm submitting a...:
Bug report (I searched for similar issues and did not find one)

## Current behavior:
Pressing enter doesn't always send messages when the option to do so is turned on. Pressing enter does, however, reliably send if one has previously pressed Shift+Enter to insert a line break during composition.

## Expected behavior:
The setting should work reliably

## Minimal reproduction of the problem with instructions:
1. Enable the "Enter to send" option
2. Type a short one-line message
3. Press enter to send the message
4. UWPX may instead insert a line break, or it may send the message (I have not been able to ascertain a pattern in its behaviour)

## Environment
App Version(s): 
v.0.19.0.0 

Windows 10 Version Number: 
- [x] 1903

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub

Where did you got the APP from?
- [x] [Windows Store](https://www.microsoft.com/store/apps/9NW16X9JB5WV)
- [ ] Self-build, using a provided release source
- [ ] Self-build, repo cloned at [dd.mm.yyy] 
- [ ] Misc, got it from...

**Comment by COM8** [comment]
Hmm yes also noticed this...
I will have a look into it.
Thanks for reporting!

**Comment by COM8** [comment]
The fix should be included in Alpha v.0.20.0.0
